### ISSUE TITLE
Update to latest resilience4j 1.5.0

### ISSUE THREAD

**Issue by Romeh** [spring-cloud/spring-cloud-circuitbreaker#72]
**Describe the bug**
can you please update resilience4j from 1.3.1 to 1.4.0 before introducing the new release of spring cloud circuit breaker ?

**Comment by breun** [comment]
Resilience4j 1.5.0 is out now: https://github.com/resilience4j/resilience4j/releases/tag/v1.5.0

This release also includes `resilience4j-bom`, which would be good to import for dependency management: https://search.maven.org/artifact/io.github.resilience4j/resilience4j-bom

**Comment by spencergibb** [comment]
We can't update to 1.5.x on hoxton, so we'll keep this open

**Comment by chrismathews** [comment]
Resilience4j 1.6.0 is out now: https://github.com/resilience4j/resilience4j/tree/v1.6.0 (actually 1.6.1 is in Maven Central but for some reason a 1.6.1 tag does not exist... which is always a bit concerning). Since 2020.0.0 is still in development I would assume moving to 1.6.x is probably a reasonable choice.

**Comment by Romeh** [comment]
the tag for 1.61 is being pushed now FYI

**Comment by breun** [comment]
The 1.6.1 release is here: https://github.com/resilience4j/resilience4j/releases/tag/v1.6.1
